import Navbar from "./Components/Navbar/Navbar";
import NewsComponent from "./Components/NewsComponent";
import React, { Component } from "react";
import "./App.css";
import { BrowserRouter as Router, Routes, Route } from "react-router-dom";

export default class App extends Component {
  render() {
    return (
      <Router>
        <div className="color">
          <Navbar country="in" />

          <Routes>
            <Route
              path=""
              element={
                <NewsComponent key="inn" category="general" country="in" />
              }
            />
            <Route
              path="/in"
              element={
                <NewsComponent key="in" category="general" country="in" />
              }
            />
            <Route
              path="/in/general"
              element={
                <NewsComponent
                  key="general-in"
                  category="general"
                  country="in"
                />
              }
            />
            <Route
              path="/in/business"
              element={
                <NewsComponent
                  key="business-ind"
                  category="business"
                  country="in"
                />
              }
            />
            <Route
              path="/in/entertainment"
              element={
                <NewsComponent
                  key="enter-ind"
                  category="entertainment"
                  country="in"
                />
              }
            />
            <Route
              path="/in/health"
              element={
                <NewsComponent key="heal-ind" category="health" country="in" />
              }
            />
            <Route
              path="/in/science"
              element={
                <NewsComponent
                  key="science-ind"
                  category="science"
                  country="in"
                />
              }
            />
            <Route
              path="/in/sports"
              element={
                <NewsComponent
                  key="sports-ind"
                  category="sports"
                  country="in"
                />
              }
            />
            <Route
              path="/in/technology"
              element={
                <NewsComponent
                  key="tech-ind"
                  category="technology"
                  country="in"
                />
              }
            />
            <Route
              path="/ae"
              element={
                <NewsComponent key="ae" category="general" country="ae" />
              }
            />
            <Route
              path="/ae/general"
              element={
                <NewsComponent
                  key="general-ae"
                  category="general"
                  country="ae"
                />
              }
            />
            <Route
              path="/ae/business"
              element={
                <NewsComponent
                  key="business-ae"
                  category="business"
                  country="ae"
                />
              }
            />
            <Route
              path="/ae/entertainment"
              element={
                <NewsComponent
                  key="enter-ae"
                  category="entertainment"
                  country="ae"
                />
              }
            />
            <Route
              path="/ae/health"
              element={
                <NewsComponent key="heal-ae" category="health" country="ae" />
              }
            />
            <Route
              path="/ae/science"
              element={
                <NewsComponent
                  key="science-ae"
                  category="science"
                  country="ae"
                />
              }
            />
            <Route
              path="/ae/sports"
              element={
                <NewsComponent key="sports-ae" category="sports" country="ae" />
              }
            />
            <Route
              path="/ae/technology"
              element={
                <NewsComponent
                  key="tech-ae"
                  category="technology"
                  country="ae"
                />
              }
            />
            <Route
              path="/ar"
              element={
                <NewsComponent key="ar" category="general" country="ar" />
              }
            />
            <Route
              path="/ar/general"
              element={
                <NewsComponent
                  key="general-ar"
                  category="general"
                  country="ar"
                />
              }
            />
            <Route
              path="/ar/business"
              element={
                <NewsComponent
                  key="business-ar"
                  category="business"
                  country="ar"
                />
              }
            />
            <Route
              path="/ar/entertainment"
              element={
                <NewsComponent
                  key="enter-ar"
                  category="entertainment"
                  country="ar"
                />
              }
            />
            <Route
              path="/ar/health"
              element={
                <NewsComponent key="heal-ar" category="health" country="ar" />
              }
            />
            <Route
              path="/ar/science"
              element={
                <NewsComponent
                  key="science-ar"
                  category="science"
                  country="ar"
                />
              }
            />
            <Route
              path="/ar/sports"
              element={
                <NewsComponent key="sports-ar" category="sports" country="ar" />
              }
            />
            <Route
              path="/ar/technology"
              element={
                <NewsComponent
                  key="tech-ar"
                  category="technology"
                  country="ar"
                />
              }
            />
            <Route
              path="/at"
              element={
                <NewsComponent key="at" category="general" country="at" />
              }
            />
            <Route
              path="/at/general"
              element={
                <NewsComponent
                  key="general-at"
                  category="general"
                  country="at"
                />
              }
            />
            <Route
              path="/at/business"
              element={
                <NewsComponent
                  key="business-at"
                  category="business"
                  country="at"
                />
              }
            />
            <Route
              path="/at/entertainment"
              element={
                <NewsComponent
                  key="enter-at"
                  category="entertainment"
                  country="at"
                />
              }
            />
            <Route
              path="/at/health"
              element={
                <NewsComponent key="heal-at" category="health" country="at" />
              }
            />
            <Route
              path="/at/science"
              element={
                <NewsComponent
                  key="science-at"
                  category="science"
                  country="at"
                />
              }
            />
            <Route
              path="/at/sports"
              element={
                <NewsComponent key="sports-at" category="sports" country="at" />
              }
            />
            <Route
              path="/at/technology"
              element={
                <NewsComponent
                  key="tech-at"
                  category="technology"
                  country="at"
                />
              }
            />
            <Route
              path="/au"
              element={
                <NewsComponent key="au" category="general" country="au" />
              }
            />
            <Route
              path="/au/general"
              element={
                <NewsComponent
                  key="general-au"
                  category="general"
                  country="au"
                />
              }
            />
            <Route
              path="/au/business"
              element={
                <NewsComponent
                  key="business-au"
                  category="business"
                  country="au"
                />
              }
            />
            <Route
              path="/au/entertainment"
              element={
                <NewsComponent
                  key="enter-au"
                  category="entertainment"
                  country="au"
                />
              }
            />
            <Route
              path="/au/health"
              element={
                <NewsComponent key="heal-au" category="health" country="au" />
              }
            />
            <Route
              path="/au/science"
              element={
                <NewsComponent
                  key="science-au"
                  category="science"
                  country="au"
                />
              }
            />
            <Route
              path="/au/sports"
              element={
                <NewsComponent key="sports-au" category="sports" country="au" />
              }
            />
            <Route
              path="/au/technology"
              element={
                <NewsComponent
                  key="tech-au"
                  category="technology"
                  country="au"
                />
              }
            />
            <Route
              path="/be"
              element={
                <NewsComponent key="be" category="general" country="be" />
              }
            />
            <Route
              path="/be/general"
              element={
                <NewsComponent
                  key="general-be"
                  category="general"
                  country="be"
                />
              }
            />
            <Route
              path="/be/business"
              element={
                <NewsComponent
                  key="business-be"
                  category="business"
                  country="be"
                />
              }
            />
            <Route
              path="/be/entertainment"
              element={
                <NewsComponent
                  key="enter-be"
                  category="entertainment"
                  country="be"
                />
              }
            />
            <Route
              path="/be/health"
              element={
                <NewsComponent key="heal-be" category="health" country="be" />
              }
            />
            <Route
              path="/be/science"
              element={
                <NewsComponent
                  key="science-be"
                  category="science"
                  country="be"
                />
              }
            />
            <Route
              path="/be/sports"
              element={
                <NewsComponent key="sports-be" category="sports" country="be" />
              }
            />
            <Route
              path="/be/technology"
              element={
                <NewsComponent
                  key="tech-be"
                  category="technology"
                  country="be"
                />
              }
            />
            <Route
              path="/br"
              element={
                <NewsComponent key="br" category="general" country="br" />
              }
            />
            <Route
              path="/br/general"
              element={
                <NewsComponent
                  key="general-br"
                  category="general"
                  country="br"
                />
              }
            />
            <Route
              path="/br/business"
              element={
                <NewsComponent
                  key="business-br"
                  category="business"
                  country="br"
                />
              }
            />
            <Route
              path="/br/entertainment"
              element={
                <NewsComponent
                  key="enter-br"
                  category="entertainment"
                  country="br"
                />
              }
            />
            <Route
              path="/br/health"
              element={
                <NewsComponent key="heal-br" category="health" country="br" />
              }
            />
            <Route
              path="/br/science"
              element={
                <NewsComponent
                  key="science-br"
                  category="science"
                  country="br"
                />
              }
            />
            <Route
              path="/br/sports"
              element={
                <NewsComponent key="sports-br" category="sports" country="br" />
              }
            />
            <Route
              path="/br/technology"
              element={
                <NewsComponent
                  key="tech-br"
                  category="technology"
                  country="br"
                />
              }
            />
            <Route
              path="/ca"
              element={
                <NewsComponent key="ca" category="general" country="ca" />
              }
            />
            <Route
              path="/ca/general"
              element={
                <NewsComponent
                  key="general-ca"
                  category="general"
                  country="ca"
                />
              }
            />
            <Route
              path="/ca/business"
              element={
                <NewsComponent
                  key="business-ca"
                  category="business"
                  country="ca"
                />
              }
            />
            <Route
              path="/ca/entertainment"
              element={
                <NewsComponent
                  key="enter-ca"
                  category="entertainment"
                  country="ca"
                />
              }
            />
            <Route
              path="/ca/health"
              element={
                <NewsComponent key="heal-ca" category="health" country="ca" />
              }
            />
            <Route
              path="/ca/science"
              element={
                <NewsComponent
                  key="science-ca"
                  category="science"
                  country="ca"
                />
              }
            />
            <Route
              path="/ca/sports"
              element={
                <NewsComponent key="sports-ca" category="sports" country="ca" />
              }
            />
            <Route
              path="/ca/technology"
              element={
                <NewsComponent
                  key="tech-ca"
                  category="technology"
                  country="ca"
                />
              }
            />
            <Route
              path="/fr"
              element={
                <NewsComponent key="fr" category="general" country="fr" />
              }
            />
            <Route
              path="/fr/general"
              element={
                <NewsComponent
                  key="general-fr"
                  category="general"
                  country="fr"
                />
              }
            />
            <Route
              path="/fr/business"
              element={
                <NewsComponent
                  key="business-fr"
                  category="business"
                  country="fr"
                />
              }
            />
            <Route
              path="/fr/entertainment"
              element={
                <NewsComponent
                  key="enter-fr"
                  category="entertainment"
                  country="fr"
                />
              }
            />
            <Route
              path="/fr/health"
              element={
                <NewsComponent key="heal-fr" category="health" country="fr" />
              }
            />
            <Route
              path="/fr/science"
              element={
                <NewsComponent
                  key="science-fr"
                  category="science"
                  country="fr"
                />
              }
            />
            <Route
              path="/fr/sports"
              element={
                <NewsComponent key="sports-fr" category="sports" country="fr" />
              }
            />
            <Route
              path="/fr/technology"
              element={
                <NewsComponent
                  key="tech-fr"
                  category="technology"
                  country="fr"
                />
              }
            />
            <Route
              path="/de"
              element={
                <NewsComponent key="de" category="general" country="de" />
              }
            />
            <Route
              path="/de/general"
              element={
                <NewsComponent
                  key="general-de"
                  category="general"
                  country="de"
                />
              }
            />
            <Route
              path="/de/business"
              element={
                <NewsComponent
                  key="business-de"
                  category="business"
                  country="de"
                />
              }
            />
            <Route
              path="/de/entertainment"
              element={
                <NewsComponent
                  key="enter-de"
                  category="entertainment"
                  country="de"
                />
              }
            />
            <Route
              path="/de/health"
              element={
                <NewsComponent key="heal-de" category="health" country="de" />
              }
            />
            <Route
              path="/de/science"
              element={
                <NewsComponent
                  key="science-de"
                  category="science"
                  country="de"
                />
              }
            />
            <Route
              path="/de/sports"
              element={
                <NewsComponent key="sports-de" category="sports" country="de" />
              }
            />
            <Route
              path="/de/technology"
              element={
                <NewsComponent
                  key="tech-de"
                  category="technology"
                  country="de"
                />
              }
            />
            <Route
              path="/ma"
              element={
                <NewsComponent key="ma" category="general" country="ma" />
              }
            />

            <Route
              path="/ma/general"
              element={
                <NewsComponent
                  key="general-ma"
                  category="general"
                  country="ma"
                />
              }
            />
            <Route
              path="/ma/business"
              element={
                <NewsComponent
                  key="business-ma"
                  category="business"
                  country="ma"
                />
              }
            />
            <Route
              path="/ma/entertainment"
              element={
                <NewsComponent
                  key="enter-ma"
                  category="entertainment"
                  country="ma"
                />
              }
            />
            <Route
              path="/ma/health"
              element={
                <NewsComponent key="heal-ma" category="health" country="ma" />
              }
            />
            <Route
              path="/ma/science"
              element={
                <NewsComponent
                  key="science-ma"
                  category="science"
                  country="ma"
                />
              }
            />
            <Route
              path="/ma/sports"
              element={
                <NewsComponent key="sports-ma" category="sports" country="ma" />
              }
            />
            <Route
              path="/ma/technology"
              element={
                <NewsComponent
                  key="tech-ma"
                  category="technology"
                  country="ma"
                />
              }
            />
            <Route
              path="/us"
              element={
                <NewsComponent key="us" category="general" country="us" />
              }
            />
            <Route
              path="/us/general"
              element={
                <NewsComponent
                  key="general-us"
                  category="general"
                  country="us"
                />
              }
            />
            <Route
              path="/us/business"
              element={
                <NewsComponent
                  key="business-us"
                  category="business"
                  country="us"
                />
              }
            />
            <Route
              path="/us/entertainment"
              element={
                <NewsComponent
                  key="enter-us"
                  category="entertainment"
                  country="us"
                />
              }
            />
            <Route
              path="/us/health"
              element={
                <NewsComponent key="heal-us" category="health" country="us" />
              }
            />
            <Route
              path="/us/science"
              element={
                <NewsComponent
                  key="science-us"
                  category="science"
                  country="us"
                />
              }
            />
            <Route
              path="/us/sports"
              element={
                <NewsComponent key="sports-us" category="sports" country="us" />
              }
            />
            <Route
              path="/us/technology"
              element={
                <NewsComponent
                  key="tech-us"
                  category="technology"
                  country="us"
                />
              }
            />
          </Routes>
        </div>
      </Router>
    );
  }
}
